/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.71).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.chencraft.api.secure;

import com.chencraft.model.FileUpload;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import jakarta.validation.Valid;
import lombok.NonNull;
import org.springframework.core.io.Resource;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import static com.chencraft.api.models.ResponseConstants.*;
import static com.chencraft.api.models.TagConstants.FILE;

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2025-08-25T12:28:47.169104610Z[Etc/UTC]")
@Validated
public interface SecureFileApi {

    @Operation(summary = "Download file from private storage", description = "Download file with private scope", security = {
            @SecurityRequirement(name = "mTLS")}, tags = {FILE})
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", ref = OK_FILE_RESPONSE),
            @ApiResponse(responseCode = "400", ref = INVALID_INPUT_RESPONSE),
            @ApiResponse(responseCode = "401", ref = UNAUTHORIZED_RESPONSE),
            @ApiResponse(responseCode = "404", ref = FILE_NOT_FOUND_RESPONSE),
            @ApiResponse(ref = INTERNAL_SERVER_ERROR_RESPONSE)})
    @RequestMapping(value = "/file/{filename}", method = RequestMethod.GET)
    ResponseEntity<@NonNull Resource> secureFile(@Parameter(in = ParameterIn.PATH, description = "Filename to be downloaded", required = true, schema = @Schema(), example = "test_connection") @PathVariable("filename") String filename
    );

    @Operation(summary = "Upload file to specific storage location", description = "Upload file to cloud storage", security = {@SecurityRequirement(name = "mTLS")}, tags = {FILE})
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "File being uploaded successfully"),
            @ApiResponse(responseCode = "400", ref = INVALID_INPUT_RESPONSE),
            @ApiResponse(responseCode = "401", ref = UNAUTHORIZED_RESPONSE),
            @ApiResponse(ref = INTERNAL_SERVER_ERROR_RESPONSE)})
    @RequestMapping(value = "/file",
            consumes = {"multipart/form-data"},
            method = RequestMethod.POST)
    ResponseEntity<?> uploadFile(@ModelAttribute @Valid FileUpload request);

    @Operation(summary = "Delete file from storage", description = "Delete file if exists",
            security = {@SecurityRequirement(name = "mTLS")}, tags = {FILE})
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "File being deleted successfully"),
            @ApiResponse(responseCode = "400", ref = INVALID_INPUT_RESPONSE),
            @ApiResponse(responseCode = "401", ref = UNAUTHORIZED_RESPONSE),
            @ApiResponse(ref = INTERNAL_SERVER_ERROR_RESPONSE)})
    @RequestMapping(value = "/file/{filename}", method = RequestMethod.DELETE)
    ResponseEntity<?> deleteFile(
            @Parameter(
                    in = ParameterIn.PATH,
                    description = "Filename to be deleted",
                    required = true,
                    schema = @Schema()
            )
            @PathVariable("filename") String filename,
            @Parameter(
                    in = ParameterIn.QUERY,
                    name = "namespace",
                    description = "Namespace for the file",
                    required = true,
                    schema = @Schema(implementation = FileUpload.Type.class, example = "PRIVATE")
            )
            @RequestParam("namespace") FileUpload.Type namespace);
}
