/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.71).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.chencraft.api;

import com.chencraft.model.GitHubWebhookRelease;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.parameters.RequestBody;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import jakarta.validation.Valid;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import static com.chencraft.api.models.ResponseConstants.*;
import static com.chencraft.api.models.TagConstants.WEBHOOK;

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2025-08-22T12:16:37.352130473Z[Etc/UTC]")
@Validated
public interface GithubWebhookApi {

    @SuppressWarnings("UastIncorrectHttpHeaderInspection")
    @Operation(
            summary = "Update files from release",
            description = "Pulls files compiled by release",
            security = {@SecurityRequirement(name = "sha256Auth")},
            tags = {WEBHOOK})
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", ref = OK_RESPONSE),
            @ApiResponse(responseCode = "401", ref = INVALID_INPUT_RESPONSE),
            @ApiResponse(responseCode = "403", ref = SIGNATURE_INVALID_RESPONSE),
            @ApiResponse(ref = INTERNAL_SERVER_ERROR_RESPONSE)})
    @RequestMapping(value = "/github_webhook/update",
            consumes = {MediaType.APPLICATION_JSON_VALUE},
            method = RequestMethod.POST)
    ResponseEntity<Void> githubWebhookUpdate(
            @RequestHeader(value = "X-Hub-Signature-256") String signature,
            @Valid @RequestBody(description = "Visit [GitHub Docs](https://docs.github.com/en/webhooks/webhook-events-and-payloads#release) for full request body", content = @Content(schema = @Schema(implementation = GitHubWebhookRelease.class))) @org.springframework.web.bind.annotation.RequestBody String rawBody
    );
}

