package com.chencraft.common.service.mail;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Lazy;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;
import org.springframework.web.util.HtmlUtils;

import java.net.InetAddress;
import java.net.UnknownHostException;

/**
 * MailService implementation backed by Spring's JavaMailSender configured for iCloud SMTP.
 * External IO: sends email via SMTP using credentials provided in configuration (app.mail.*).
 */
@Slf4j
@Lazy
@Service
public class iCloudMailService implements MailService {
    private final JavaMailSender mailSender;

    @Value("${app.mail.sender}")
    private String sender;

    @Value("${spring.application.name}")
    private String appName;

    /**
     * Creates the iCloudMailService.
     *
     * @param mailSender JavaMailSender configured for iCloud SMTP
     */
    @Autowired
    public iCloudMailService(@SuppressWarnings("SpringJavaInjectionPointsAutowiringInspection") JavaMailSender mailSender) {
        this.mailSender = mailSender;
    }

    @Override
    public void sendMail(String to, MailFlag flag, String subject, String body) {
        try {
            MimeMessage mimeMessage = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(mimeMessage, "UTF-8");

            helper.setFrom(sender);
            helper.setTo(to);
            helper.setSubject("[%s] %s".formatted(flag, subject));

            String htmlBody = HtmlUtils.htmlEscape(body).replace("\n", "<br>") + "<br><br>" + generateFooterHtml();
            helper.setText(htmlBody, true);

            mailSender.send(mimeMessage);
        } catch (MessagingException e) {
            log.error("Failed to send email to {}", to, e);
        }
    }

    private String generateFooterHtml() {
        String hostName;
        try {
            hostName = InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException e) {
            hostName = "unknown-host";
        }

        return """
                <hr style="border:none;border-top:1px solid #eee;margin:20px 0;">
                <div style="color:#888;font-size:0.8em;font-family:sans-serif;">
                  <p>[auto-generated by %s on %s]</p>
                  <p><i>Disclaimer: This email and any attachments are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error, please notify the system manager.</i></p>
                </div>
                """.formatted(appName, hostName);
    }
}
